;PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
; We have to keep libdeps dir out the project directory otherwise,
; library scanner seems to have issues so compilation fails
libdeps_dir = /tmp/libdeps
src_dir = .

;--- Custom LED driver board Demo board --------------------------------------------------
[env:stm32l071cb]
platform = ststm32
board = genericSTM32L071CBT6
framework = arduino
board_build.f_cpu = 16000000L

; We consider that the this projects is opened within its project directory
; while working with VS Code.
lib_extra_dirs = ../../../

lib_deps =
  knx

monitor_speed = 115200

; TODO: Fix pin associations.
build_flags =
  -DHSE_VALUE=16000000U
  -DCLOCK_SOURCE=CLOCK_HS
  -DENABLE_HWSERIAL4
  -DENABLE_HWSERIAL5
  -DPIN_SERIAL_TX=PB_3 ;debug serial
  -DPIN_SERIAL_RX=PB_4 ;debug serial
  -DPIN_SERIAL5_TX=PB_3 ;3 ;debug serial
  -DPIN_SERIAL5_RX=PB_4 ;4 ;debug serial
  -DPIN_SERIAL4_TX=PA_0
  -DPIN_SERIAL4_RX=PA_1
  -DSERIAL_UART_INSTANCE=5
  -DKNX_SERIAL=Serial4 ;It defines the KNX_SERIAL macro that will be equal to Serial1 it will override the default on, which is the Serial2 in case of stm32
  -DKNX_BUTTON=PA_6
  -DKNX_LED=PB_2
  -DKNX_LED_ACTIVE_ON=1 ;KNX led is active on, so if I drive the prog led, it will be on
  -DMASK_VERSION=0x07B0
  -Wno-unknown-pragmas

extra_scripts = ../scripts/stm32rdu.py

;--- NCN5121 Demo board --------------------------------------------------
[env:nucleo-f103]
platform = ststm32
board = nucleo_f103rb
framework = arduino
; We consider that the this projects is opened within its project directory
; while working with VS Code.
lib_extra_dirs = ../../../

lib_deps =
  knx

; TODO: Fix pin associations.
build_flags =
  -DENABLE_HWSERIAL3
  -DENABLE_HWSERIAL2
  -DPIN_SERIAL_TX=PC10
  -DPIN_SERIAL_RX=PC11
  -DPIN_SERIAL3_TX=PC10
  -DPIN_SERIAL3_RX=PC11
  -DPIN_SERIAL2_TX=PA2
  -DPIN_SERIAL2_RX=PA3
  -DSERIAL_UART_INSTANCE=3
  -DKNX_SERIAL=Serial2 ;It defines the KNX_SERIAL macro that will be equal to Serial1 it will override the default on, which is the Serial2 in case of stm32
  -DKNX_BUTTON=PC1
  -DKNX_LED=PB0
  -DMASK_VERSION=0x07B0
  -Wno-unknown-pragmas

extra_scripts = ../scripts/stm32rdu.py

;--- SAMD --------------------------------------------------
[env:adafruit_feather_m0_rf]
platform = atmelsam
board = adafruit_feather_m0
framework = arduino
; We consider that the this projects is opened within its project directory
; while working with VS Code.
lib_extra_dirs = ../../../

lib_deps =
  SPI
  knx

build_flags =
  -DMASK_VERSION=0x27B0
  -Wno-unknown-pragmas
;-----------------------------------------------------------


;--- ESP8266 -----------------------------------------------
#[env:nodemcuv2_ip]
#platform = espressif8266
#board = nodemcuv2
#framework = arduino
; We consider that the this projects is opened within its project directory
; while working with VS Code.
#lib_extra_dirs = ../../../

#lib_deps =
#  WifiManager
#  knx

#build_flags =
#  -DMASK_VERSION=0x57B0
#  -Wno-unknown-pragmas

[env:nodemcuv2_tp]
platform = espressif8266@^2
board = nodemcuv2
framework = arduino
; We consider that the this projects is opened within its project directory
; while working with VS Code.
lib_extra_dirs = ../../../

lib_deps =
  WifiManager@0.15.0
  knx

build_flags =
  -DMASK_VERSION=0x07B0
  -Wno-unknown-pragmas

;---------------------------------------------------------


;--- ESP32 -----------------------------------------------
[env:esp32dev_ip]
platform = espressif32
board = esp32dev
framework = arduino
; We consider that the this projects is opened within its project directory
; while working with VS Code.
lib_extra_dirs = ../../../

lib_deps =
  https://github.com/tzapu/WiFiManager.git
  knx

build_flags =
  -DMASK_VERSION=0x57B0
  -Wno-unknown-pragmas

[env:esp32dev_tp]
platform = espressif32
board = esp32dev
framework = arduino
; We consider that the this projects is opened within its project directory
; while working with VS Code.
lib_extra_dirs = ../../../

lib_deps =
  knx

build_flags =
  -DMASK_VERSION=0x07B0
  -Wno-unknown-pragmas

;--- STM32/GD32 ---
[env:h8i8o]
platform = ststm32
board = genericSTM32F103CB
framework = arduino
; We consider that the this projects is opened within its project directory
; while working with VS Code.
lib_extra_dirs = ../../../

lib_deps =
  knx

build_flags =
  -DENABLE_HWSERIAL1
  -DPIN_SERIAL1_TX=PA9
  -DPIN_SERIAL1_RX=PA10
  -DKNX_SERIAL=Serial1
  -DKNX_BUTTON=PA11
  -DKNX_LED=PA12
  -DMASK_VERSION=0x07B0
  -Wno-unknown-pragmas

extra_scripts = ../scripts/stm32rdu.py

[env:h8c09]
platform = ststm32
board = genericSTM32F103CB
framework = arduino
; We consider that the this projects is opened within its project directory
; while working with VS Code.
lib_extra_dirs = ../../../

lib_deps =
  knx

build_flags =
  -DENABLE_HWSERIAL1
  -DPIN_SERIAL1_TX=PA9
  -DPIN_SERIAL1_RX=PA10
  -DKNX_SERIAL=Serial1
  -DKNX_BUTTON=PB0
  -DKNX_LED=PB5
  -DMASK_VERSION=0x07B0
  -Wno-unknown-pragmas

extra_scripts = ../scripts/stm32rdu.py


;--- RP2040 -----------------------------------------------
[env:rp2040]
framework = arduino
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#60d6ae8
platform_packages = framework-arduinopico @ https://github.com/earlephilhower/arduino-pico/releases/download/3.9.3/rp2040-3.9.3.zip
board = rpipico
board_build.core = earlephilhower
; We consider that the this projects is opened within its project directory
; while working with VS Code.


lib_deps =
  knx=file://../../../knx

lib_ldf_mode = deep+

build_flags =
  -DMASK_VERSION=0x07B0
  -DKNX_FLASH_SIZE=4096
  -D PIO_FRAMEWORK_ARDUINO_ENABLE_RTTI
  -Wno-unknown-pragmas

;--- LibreTiny BK7231N ------------------------------------
[env:BK7231N_ip]
platform = libretiny
board = cbu
framework = arduino
; We consider that the this projects is opened within its project directory
; while working with VS Code.
lib_extra_dirs = ../../../

lib_deps =
  knx

build_flags =
  -DMASK_VERSION=0x57B0
  -DKNX_NO_SPI
  -DKNX_FLASH_OFFSET=0x1DB000
  -Wno-unknown-pragmas